# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "42981728df5709e8343aa4350572a918"
name = "optimized-account-app"
handle = "optimized-account-app-6"
application_url = "https://sunny-nicole-adopt-bumper.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-sample-store-1.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sunny-nicole-adopt-bumper.trycloudflare.com/auth/callback",
  "https://sunny-nicole-adopt-bumper.trycloudflare.com/auth/shopify/callback",
  "https://sunny-nicole-adopt-bumper.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
