# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7690da1ea23f3e5ba237d5b3356699ff"
name = "payment-test"
handle = "payment-test-76"
application_url = "https://expires-detect-improvement-spreading.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_billing,read_products,write_billing,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://expires-detect-improvement-spreading.trycloudflare.com/auth/callback",
  "https://expires-detect-improvement-spreading.trycloudflare.com/auth/shopify/callback",
  "https://expires-detect-improvement-spreading.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
